services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    ports:
      - 3000:3000
    volumes:
      - ./volume/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - ./volume/homepage_imgs:/app/public/images
    restart: unless-stopped